import { Inter } from 'next/font/google'
import './globals.css'
import './style.css'
import Navbar from '@/src/Shared/Navbar'
import Footer from '@/src/Shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sakib Talukqder',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='mx-0 md:mx-12 lg:mx-16 xl:mx-20'>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
